#! /bin/sh

#########################################################################
# Copyright (C) 2008 Tavian Barnes <tavianator@gmail.com>               #
#                                                                       #
# This file is part of The FPFD Library Build Suite                     #
#                                                                       #
# The FPFD Library Build Suite is free software; you can redistribute   #
# it and/or modify it under the terms of the GNU General Public License #
# as published by the Free Software Foundation; either version 3 of the #
# License, or (at your option) any later version.                       #
#                                                                       #
# The FPFD Library Build Suite is distributed in the hope that it will  #
# be useful, but WITHOUT ANY WARRANTY; without even the implied         #
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See #
# the GNU General Public License for more details.                      #
#                                                                       #
# You should have received a copy of the GNU General Public License     #
# along with this program.  If not, see <http://www.gnu.org/licenses/>. #
#########################################################################

cat <<EOF
/* Automatically generated by libfpfd-dpd/x86/multable-x86.sh */

        .data
.globl fpfd_bcdmul
        .align 32
        .type fpfd_bcdmul, @object
        .size fpfd_bcdmul, 78336
fpfd_bcdmul:
EOF

for ((lhs=0x00; lhs<=0x99; ++lhs))
do
    for ((rhs=0x00; rhs<0x100; ++rhs))
    do
#        lhs_dec=$(printf '%x' $lhs | sed 's/[a-f]/1/g')
#        rhs_dec=$(printf '%x' $rhs | sed 's/[a-f]/1/g')
#        echo "        .value 0x$[$lhs_dec*$rhs_dec]"
        lhs_dec=$(printf '%X' $lhs)
        rhs_dec=$(printf '%X' $rhs)
        echo "        .value 0x$(echo $lhs_dec*$rhs_dec | bc)"
    done
done
